name = input('What is your name?')
age = int(input('What is your age?'))
brotherDiff = int(input('How big your brother than you'))
print('Name', name)
print('Age ' , age)
print("Brother's age", int(brotherDiff + age))